mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
proxies:
- name: (01) -  t.me/rjsxrd (VMESS)
  type: vmess
  server: 165.140.216.142
  port: 443
  uuid: b65a2d69-5634-42a2-e4be-54e8a6176900
  alterId: 0
  cipher: auto
  udp: true
  network: tcp
- name: (02) - [OpenRay] 🇨🇦 CA-25340 (VLESS)
  type: vless
  server: 104.17.101.139
  port: 2095
  uuid: 86c50e3a-5b87-49dd-bd20-03c7f2735e40
  udp: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: fangbinxingnmsl.pusytroller.gq
- name: (03) -  t.me/rjsxrd (VMESS)
  type: vmess
  server: 129.146.77.248
  port: 39495
  uuid: f836c736-87fc-4fde-aabc-00857ecdff3e
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /cctv13.m3u8
- name: (04) - [OpenRay] 🇨🇦 CA-27827 (VMESS)
  type: vmess
  server: 134.195.196.211
  port: 18000
  uuid: f8c8dc3d-0d37-46b0-8b34-a7232882fcfe
  alterId: 0
  cipher: auto
  udp: true
  network: tcp
  servername: '@proxyvpn11'
- name: (05) -  t.me/rjsxrd (VMESS)
  type: vmess
  server: 67.220.95.3
  port: 18000
  uuid: f8c8dc3d-0d37-46b0-8b34-a7232882fcfe
  alterId: 0
  cipher: aes-128-gcm
  udp: true
  network: tcp
- name: (06) - 440.🌐Неизвестно | @LimeVPNFREE t.me/rjsxrd (VLESS)
  type: vless
  server: 130.107.73.148
  port: 41373
  uuid: a71c8954-66a8-4321-bedb-2336230d81ce
  udp: true
  network: tcp
  tls: true
  servername: google.com
  client-fingerprint: chrome
  flow: xtls-rprx-vision
  reality-opts:
    public-key: m0GsZOAwvAJEaqh9aH6qfOmBKo0KW0jY_tJEC6KaDEU
    short-id: 0e
- name: (07) - 🇺🇸 (VLESS)
  type: vless
  server: 169.40.42.225
  port: 443
  uuid: d65cc14c-f53f-4fe2-b262-97856601319c
  udp: true
  network: tcp
  tls: true
  servername: yahoo.com
  client-fingerprint: chrome
  flow: xtls-rprx-vision
  reality-opts:
    public-key: e2RLf57Li_-MDZGE9ss1BWPgP54mqRb5PfXhW2jcVVg
    short-id: c39cc7310a
- name: (08) - Server 3 (VLESS)
  type: vless
  server: 169.40.42.184
  port: 443
  uuid: d65cc14c-f53f-4fe2-b262-97856601319c
  udp: true
  network: tcp
  tls: true
  servername: yahoo.com
  client-fingerprint: ios
  flow: xtls-rprx-vision
  reality-opts:
    public-key: e2RLf57Li_-MDZGE9ss1BWPgP54mqRb5PfXhW2jcVVg
    short-id: c39cc7310a
- name: (09) - 🇬🇧telegram➠@v2rayNG_Matsuri (VLESS)
  type: vless
  server: 169.40.42.179
  port: 443
  uuid: d65cc14c-f53f-4fe2-b262-97856601319c
  udp: true
  network: tcp
  tls: true
  servername: yahoo.com
  client-fingerprint: ios
  flow: xtls-rprx-vision
  reality-opts:
    public-key: e2RLf57Li_-MDZGE9ss1BWPgP54mqRb5PfXhW2jcVVg
    short-id: c39cc7310a
- name: (10) - 🇸🇪 (VLESS)
  type: vless
  server: swa.mythos-wargame.fun
  port: 443
  uuid: 2dd48980-5c2a-4f3b-bc8f-e20a8ae24ab1
  udp: true
  network: grpc
  tls: true
  client-fingerprint: qq
  grpc-opts:
    grpc-service-name: edge.sync.v1
- name: (11) - [OpenRay] 🇨🇦 CA-19477 (VLESS)
  type: vless
  server: 188.114.97.6
  port: 443
  uuid: b2f6aa3a-2550-4a1c-b2c0-1c94b1207217
  udp: true
  network: ws
  tls: true
  servername: terazhediii.info
  client-fingerprint: chrome
  ws-opts:
    path: /hdgrbws
    headers:
      Host: terazhediii.info
- name: (12) - [OpenRay] 🇨🇦 CA-25133 (VLESS)
  type: vless
  server: cf.levikogjgfdd.ir
  port: 443
  uuid: b2f6aa3a-2550-4a1c-b2c0-1c94b1207217
  udp: true
  network: ws
  tls: true
  servername: terazhediii.info
  client-fingerprint: chrome
  ws-opts:
    path: /hdgrbws
    headers:
      Host: terazhediii.info
- name: (13) - [OpenRay] 🇨🇦 CA-21007 (VLESS)
  type: vless
  server: 104.17.121.110
  port: 443
  uuid: b2f6aa3a-2550-4a1c-b2c0-1c94b1207217
  udp: true
  network: ws
  tls: true
  servername: terazhediii.info
  client-fingerprint: chrome
  ws-opts:
    path: /hdgrbws
    headers:
      Host: terazhediii.info
- name: (14) - 🇪🇪 (VLESS)
  type: vless
  server: eeb.webinarly.fun
  port: 443
  uuid: 2dd48980-5c2a-4f3b-bc8f-e20a8ae24ab1
  udp: true
  network: grpc
  tls: true
  servername: eeb.webinarly.fun
  client-fingerprint: chrome
  grpc-opts:
    grpc-service-name: edge.sync.v1
- name: (15) - 🇷🇺 (VLESS)
  type: vless
  server: 31.76.84.62
  port: 443
  uuid: 791a171e-c0af-4bd7-b8ce-43541c7585db
  udp: true
  network: grpc
  tls: true
  servername: id.pervye.ru
  client-fingerprint: chrome
  reality-opts:
    public-key: QZz4tjRkxYsgTZBlRALOQU4O5YnAGtSGkXF8OSX11m8
  grpc-opts:
    grpc-service-name: ns
- name: (16) - [OpenRay] 🇨🇦 CA-27502 (VLESS)
  type: vless
  server: 104.19.229.21
  port: 443
  uuid: b2f6aa3a-2550-4a1c-b2c0-1c94b1207217
  udp: true
  network: ws
  tls: true
  servername: terazhediii.info
  client-fingerprint: chrome
  ws-opts:
    path: /hdgrbws
    headers:
      Host: terazhediii.info
- name: (17) - [OpenRay] 🇨🇦 CA-27487 (VLESS)
  type: vless
  server: 104.16.62.25
  port: 443
  uuid: b2f6aa3a-2550-4a1c-b2c0-1c94b1207217
  udp: true
  network: ws
  tls: true
  servername: terazhediii.info
  client-fingerprint: chrome
  ws-opts:
    path: /hdgrbws
    headers:
      Host: terazhediii.info
- name: (18) - 🇰🇷 (VLESS)
  type: vless
  server: 3.39.4.109
  port: 13672
  uuid: 814bd064-544d-4255-a070-5705c03f6da9
  udp: true
  network: tcp
  tls: true
  servername: www.apple.com
  client-fingerprint: chrome
  flow: xtls-rprx-vision
  reality-opts:
    public-key: k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0
    short-id: 48050fab
- name: (19) - [OpenRay] 🇨🇦 CA-27530 (VLESS)
  type: vless
  server: 104.16.80.73
  port: 443
  uuid: b2f6aa3a-2550-4a1c-b2c0-1c94b1207217
  udp: true
  network: ws
  tls: true
  servername: terazhediii.info
  client-fingerprint: chrome
  ws-opts:
    path: /hdgrbws
    headers:
      Host: terazhediii.info
- name: (20) - [OpenRay] 🇨🇦 CA-27522 (VLESS)
  type: vless
  server: 104.16.118.43
  port: 443
  uuid: b2f6aa3a-2550-4a1c-b2c0-1c94b1207217
  udp: true
  network: ws
  tls: true
  servername: terazhediii.info
  client-fingerprint: chrome
  ws-opts:
    path: /hdgrbws
    headers:
      Host: terazhediii.info
- name: (21) - [OpenRay] 🇨🇦 CA-26787 (VLESS)
  type: vless
  server: 188.114.97.3
  port: 443
  uuid: b2f6aa3a-2550-4a1c-b2c0-1c94b1207217
  udp: true
  network: ws
  tls: true
  servername: terazhediii.info
  client-fingerprint: chrome
  ws-opts:
    path: /hdgrbws
    headers:
      Host: terazhediii.info
- name: (22) - 🇮🇹 Italy [*CIDR] t.me/rjsxrd (VLESS)
  type: vless
  server: 104.171.128.225
  port: 443
  uuid: d900a139-8b5f-4758-8a32-389c6f36fc86
  udp: true
  network: grpc
  tls: true
  servername: dl.google.com
  client-fingerprint: ios
  reality-opts:
    public-key: eNvO4-6_VFngHHC6D5AhcCpCpOdi5gY7-Srimhh-6Xw
  grpc-opts:
    grpc-service-name: grpc-tunnel
- name: (23) - 🇮🇹 Italy [*CIDR] t.me/rjsxrd (VLESS)
  type: vless
  server: 104.171.128.225
  port: 443
  uuid: 4fe19d97-7b1d-4cb2-99ee-4bd8658a4c34
  udp: true
  network: grpc
  tls: true
  servername: dl.google.com
  client-fingerprint: qq
  reality-opts:
    public-key: eNvO4-6_VFngHHC6D5AhcCpCpOdi5gY7-Srimhh-6Xw
  grpc-opts:
    grpc-service-name: grpc-tunnel
- name: '(24) - 🇳🇱 Netherlands | TG: @HardVpn_robot t.me/rjsxrd (VLESS)'
  type: vless
  server: 154.83.246.52
  port: 443
  uuid: c90f26f0-5a20-4573-a31a-c27b3c96933e
  udp: true
  network: tcp
  tls: true
  servername: storage.yandex.net
  client-fingerprint: edge
  flow: xtls-rprx-vision
  reality-opts:
    public-key: pPi-WO8qQFFZ9UJWNLW9YClbjcoAAZWJQ2_FM3Kjhz8
    short-id: 500aec9e9e5e2212
- name: '(25) - 🇫🇷 France | TG: @HardVpn_robot t.me/rjsxrd (VLESS)'
  type: vless
  server: 45.192.2.72
  port: 443
  uuid: 219762a7-b918-4e2b-8a3d-d309ef98bb61
  udp: true
  network: tcp
  tls: true
  servername: storage.yandex.net
  client-fingerprint: firefox
  flow: xtls-rprx-vision
  reality-opts:
    public-key: 1oUeBtHH4DskTM_jCh-6enWRkFMDX9l1OU5kWYl4kxA
    short-id: 364994a6f61fc955
- name: (26) - 🇫🇷 (VLESS)
  type: vless
  server: 62.210.91.2
  port: 23576
  uuid: 48ff2b70-e180-582f-8866-d9a2edeed5f5
  udp: true
  network: tcp
  tls: true
  servername: fuck.rkn
  client-fingerprint: chrome
  flow: xtls-rprx-vision
  reality-opts:
    public-key: 1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s
    short-id: '01'
- name: (27) - 🇮🇹 Italy [*CIDR] t.me/rjsxrd (VLESS)
  type: vless
  server: 104.171.128.225
  port: 443
  uuid: 75079a7f-75b5-418b-8a65-f7b2f438cd4a
  udp: true
  network: grpc
  tls: true
  servername: dl.google.com
  client-fingerprint: chrome
  reality-opts:
    public-key: eNvO4-6_VFngHHC6D5AhcCpCpOdi5gY7-Srimhh-6Xw
  grpc-opts:
    grpc-service-name: grpc-tunnel
- name: (28) - 🇩🇪_德国_17 t.me/rjsxrd (VLESS)
  type: vless
  server: bla-bla-bla-de.anti-zapret.com
  port: 8443
  uuid: d11613a1-2e1f-eac4-a275-aabd986b7ad1
  udp: true
  network: tcp
  tls: true
  servername: bla-bla-bla-de.anti-zapret.com
  client-fingerprint: firefox
  reality-opts:
    public-key: 0AVsyS7udTbxKRdSyQ2rtFC63icDQOVWq8FvAhhU-WY
    short-id: 17faf32cb516c9cb
- name: (29) - 🇮🇹 Italy [*CIDR] t.me/rjsxrd (VLESS)
  type: vless
  server: 104.171.128.225
  port: 443
  uuid: 626c0789-16d1-4815-be8b-bd03959d7d12
  udp: true
  network: grpc
  tls: true
  servername: dl.google.com
  client-fingerprint: edge
  reality-opts:
    public-key: eNvO4-6_VFngHHC6D5AhcCpCpOdi5gY7-Srimhh-6Xw
  grpc-opts:
    grpc-service-name: grpc-tunnel
- name: (30) - 🇯🇵 (VLESS)
  type: vless
  server: 3.114.220.22
  port: 10583
  uuid: 814bd064-544d-4255-a070-5705c03f6da9
  udp: true
  network: tcp
  tls: true
  servername: www.apple.com
  client-fingerprint: chrome
  flow: xtls-rprx-vision
  reality-opts:
    public-key: k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0
    short-id: 48050fab
- name: (31) - 🇩🇪 德国 | DEU t.me/rjsxrd (VLESS)
  type: vless
  server: 157.173.7.55
  port: 443
  uuid: 64774bd8-3116-4eaa-a046-5ea4fc230b81
  udp: true
  network: tcp
  tls: true
  servername: node-fra01.rkitman.ru
  client-fingerprint: firefox
  flow: xtls-rprx-vision
  reality-opts:
    public-key: 8C7evg_SSrJbxMTaUqJoylqB9HSNsmBvmUlgs_c5EiU
    short-id: 88d9dc52ef39c8bd
- name: (32) - 🇩🇪 (VLESS)
  type: vless
  server: nodefulcrum.mooo.com
  port: 443
  uuid: d4d4d103-5074-47e9-96e6-5431f4e35c57
  udp: true
  network: tcp
  tls: true
  servername: nodefulcrum.mooo.com
  client-fingerprint: chrome
  flow: xtls-rprx-vision
  reality-opts:
    public-key: IhbpvWBZmJEzDs4eI2zoFmL_a-1J_7Z7Sepyrn7-xF8
    short-id: 6547735997055a35
- name: (33) - 🇳🇱_荷兰_25 t.me/rjsxrd (VLESS)
  type: vless
  server: 87.121.221.253
  port: 443
  uuid: 423b1d79-08c4-403f-9d5e-c541f791b55f
  udp: true
  network: tcp
  tls: true
  servername: eu-west.cendora.ru
  client-fingerprint: qq
  flow: xtls-rprx-vision
  reality-opts:
    public-key: m6RDw1b8R4lCaRUIzhHpy6TtX2Dhk6nyby8dWzeQqA0
    short-id: dd3ff38418d29d22
- name: (34) - 🇩🇪_德国_19 t.me/rjsxrd (VLESS)
  type: vless
  server: node-fra01.rkitman.ru
  port: 443
  uuid: 64774bd8-3116-4eaa-a046-5ea4fc230b81
  udp: true
  network: tcp
  tls: true
  client-fingerprint: safari
  flow: xtls-rprx-vision
  reality-opts:
    public-key: 8C7evg_SSrJbxMTaUqJoylqB9HSNsmBvmUlgs_c5EiU
    short-id: 88d9dc52ef39c8bd
- name: (35) - 🇩🇪_德国_21 t.me/rjsxrd (VLESS)
  type: vless
  server: 157.173.7.200
  port: 443
  uuid: 64774bd8-3116-4eaa-a046-5ea4fc230b81
  udp: true
  network: tcp
  tls: true
  servername: node-fra02.rkitman.ru
  client-fingerprint: firefox
  flow: xtls-rprx-vision
  reality-opts:
    public-key: 8C7evg_SSrJbxMTaUqJoylqB9HSNsmBvmUlgs_c5EiU
    short-id: 88d9dc52ef39c8bd
- name: (36) - 14 (VLESS)
  type: vless
  server: 147.45.173.79
  port: 443
  uuid: 2d533930-577c-46b6-b53d-4dd4cdc0b458
  udp: true
  network: tcp
  tls: true
  servername: app.restorium.su
  client-fingerprint: firefox
  flow: xtls-rprx-vision
  reality-opts:
    public-key: SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY
    short-id: fd55b698ee8c3629
- name: (37) - 🇩🇪 (VLESS)
  type: vless
  server: node-fra02.rkitman.ru
  port: 443
  uuid: 64774bd8-3116-4eaa-a046-5ea4fc230b81
  udp: true
  network: tcp
  tls: true
  servername: node-fra02.rkitman.ru
  client-fingerprint: chrome
  flow: xtls-rprx-vision
  reality-opts:
    public-key: 8C7evg_SSrJbxMTaUqJoylqB9HSNsmBvmUlgs_c5EiU
    short-id: 88d9dc52ef39c8bd
- name: (38) - 🇳🇱_荷兰_58 t.me/rjsxrd (VLESS)
  type: vless
  server: 94.183.255.157
  port: 443
  uuid: 41e71ba7-d389-47aa-94f7-ed1f55fdbcdf
  udp: true
  network: tcp
  tls: true
  servername: cdnjs.com
  client-fingerprint: firefox
  flow: xtls-rprx-vision
  reality-opts:
    public-key: E1te_g9q6EWQVOCgjwI4PF-cml9qqW7OEAf33tYkUxQ
    short-id: 17d334ad29b2ff40
- name: (39) - 🇳🇱_荷兰_61 t.me/rjsxrd (VLESS)
  type: vless
  server: 94.183.255.103
  port: 443
  uuid: 423b1d79-08c4-403f-9d5e-c541f791b55f
  udp: true
  network: tcp
  tls: true
  servername: eu-west.cendora.ru
  client-fingerprint: qq
  flow: xtls-rprx-vision
  reality-opts:
    public-key: m6RDw1b8R4lCaRUIzhHpy6TtX2Dhk6nyby8dWzeQqA0
    short-id: dd3ff38418d29d22
- name: '(40) - 🇨🇭 Switzerland | TG: @HardVpn_robot t.me/rjsxrd (VLESS)'
  type: vless
  server: 45.196.193.100
  port: 443
  uuid: 219762a7-b918-4e2b-8a3d-d309ef98bb61
  udp: true
  network: tcp
  tls: true
  servername: storage.yandex.net
  client-fingerprint: chrome
  flow: xtls-rprx-vision
  reality-opts:
    public-key: IdqrygjwHBEMCOamBl7a504TVk6uMAtTRj0xLWcFcxY
    short-id: 40ce08cf20c67003
- name: (41) - 🇦🇪_阿拉伯联合酋长国_57 t.me/rjsxrd (VLESS)
  type: vless
  server: 151.242.160.111
  port: 443
  uuid: 423b1d79-08c4-403f-9d5e-c541f791b55f
  udp: true
  network: tcp
  tls: true
  servername: eu-central.cendora.ru
  client-fingerprint: qq
  flow: xtls-rprx-vision
  reality-opts:
    public-key: b-Cm9hX-3UHsS1L_lnUB6AMjuKhlN1IDdBbZ506itjI
    short-id: 00bca5982f82d083
- name: (42) - 🇵🇱_波兰_53 t.me/rjsxrd (VLESS)
  type: vless
  server: 31.59.125.49
  port: 443
  uuid: 423b1d79-08c4-403f-9d5e-c541f791b55f
  udp: true
  network: tcp
  tls: true
  servername: eu-central.cendora.ru
  client-fingerprint: firefox
  flow: xtls-rprx-vision
  reality-opts:
    public-key: b-Cm9hX-3UHsS1L_lnUB6AMjuKhlN1IDdBbZ506itjI
    short-id: 00bca5982f82d083
- name: (43) - 🇳🇱 荷兰 | NLD t.me/rjsxrd (VLESS)
  type: vless
  server: edge-cache07.go-vpn.club
  port: 443
  uuid: 41e71ba7-d389-47aa-94f7-ed1f55fdbcdf
  udp: true
  network: tcp
  tls: true
  servername: cdnjs.com
  client-fingerprint: firefox
  flow: xtls-rprx-vision
  reality-opts:
    public-key: E1te_g9q6EWQVOCgjwI4PF-cml9qqW7OEAf33tYkUxQ
    short-id: 17d334ad29b2ff40
- name: (44) - 🇪🇸 (VLESS)
  type: vless
  server: bc-es-hn.ray-balance.space
  port: 443
  uuid: 710fc22f-06b2-4b6d-bb3e-f57c17b670a6
  udp: true
  network: tcp
  tls: true
  servername: www.ray-balance.space
  client-fingerprint: chrome
  flow: xtls-rprx-vision
  reality-opts:
    public-key: d1NlaZfnsYjWfxRTqIBk1ldBUmdE-kRTEQ_sWd1JYwI
- name: (45) - 🇳🇴_挪威_60 t.me/rjsxrd (VLESS)
  type: vless
  server: 151.242.169.44
  port: 443
  uuid: ae0d03aa-6e1e-433f-864e-06b49ed2737c
  udp: true
  network: tcp
  tls: true
  servername: frantax.my3cx.de
  client-fingerprint: firefox
  flow: xtls-rprx-vision
  reality-opts:
    public-key: oXYB-DXrI08UVBRFq8MERP36betSSd7Yb6MLN88F2R4
    short-id: f6b5862c1f73ab80
- name: '(46) - اگه میخوای قطع نشی جوین شو : @farsiproxy (VLESS)'
  type: vless
  server: 169.40.42.15
  port: 443
  uuid: d65cc14c-f53f-4fe2-b262-97856601319c
  udp: true
  network: tcp
  tls: true
  servername: yahoo.com
  client-fingerprint: firefox
  flow: xtls-rprx-vision
  reality-opts:
    public-key: e2RLf57Li_-MDZGE9ss1BWPgP54mqRb5PfXhW2jcVVg
    short-id: c39cc7310a
- name: (47) - 🇩🇪 (VLESS)
  type: vless
  server: 51.77.76.61
  port: 8444
  uuid: 1f619326-cd93-4d6b-aebe-e0b5f8831d02
  udp: true
  network: ws
  tls: true
  servername: link.meshbeat.online
  client-fingerprint: firefox
  ws-opts:
    path: /api/v1/devices/ff3c56308c/telemetry
    headers:
      Host: link.meshbeat.online
- name: (48) - 🇷🇺 Russia [*CIDR] t.me/rjsxrd (VLESS)
  type: vless
  server: 185.147.26.216
  port: 443
  uuid: d11613a1-2e1f-4209-a275-aabd986b7ad1
  udp: true
  network: raw
  tls: true
  servername: ru.srv.anti-zapret.com
  client-fingerprint: firefox
  flow: xtls-rprx-vision
  reality-opts:
    public-key: 0AVsyS7udTbxKRdSyQ2rtFC63icDQOVWq8FvAhhU-WY
    short-id: 17faf32cb516c9cb
- name: (49) - 🇷🇺 Russia [*CIDR] t.me/rjsxrd (VLESS)
  type: vless
  server: s4.arch.anti-zapret.com
  port: 443
  uuid: d11613a1-2e1f-4209-a275-aabd986b7ad1
  udp: true
  network: tcp
  tls: true
  servername: ru.srv.anti-zapret.com
  client-fingerprint: firefox
  flow: xtls-rprx-vision
  reality-opts:
    public-key: 0AVsyS7udTbxKRdSyQ2rtFC63icDQOVWq8FvAhhU-WY
    short-id: 17faf32cb516c9cb
- name: (50) - 🇩🇪 (VLESS)
  type: vless
  server: 31.76.111.113
  port: 7777
  uuid: 9e09f1ce-45d4-466d-b077-81b0dae00db2
  udp: true
  network: tcp
  tls: true
  servername: console.cloud.yandex.ru
  client-fingerprint: firefox
  flow: xtls-rprx-vision
  reality-opts:
    public-key: 4iWZChsH0rnqtn89xiB1evDLkFjmgh-3WYjx8cknZC0
    short-id: a8b9c0d1e2f34567
proxy-groups:
- name: TOP
  type: select
  proxies:
  - (01) -  t.me/rjsxrd (VMESS)
  - (02) - [OpenRay] 🇨🇦 CA-25340 (VLESS)
  - (03) -  t.me/rjsxrd (VMESS)
  - (04) - [OpenRay] 🇨🇦 CA-27827 (VMESS)
  - (05) -  t.me/rjsxrd (VMESS)
  - (06) - 440.🌐Неизвестно | @LimeVPNFREE t.me/rjsxrd (VLESS)
  - (07) - 🇺🇸 (VLESS)
  - (08) - Server 3 (VLESS)
  - (09) - 🇬🇧telegram➠@v2rayNG_Matsuri (VLESS)
  - (10) - 🇸🇪 (VLESS)
  - (11) - [OpenRay] 🇨🇦 CA-19477 (VLESS)
  - (12) - [OpenRay] 🇨🇦 CA-25133 (VLESS)
  - (13) - [OpenRay] 🇨🇦 CA-21007 (VLESS)
  - (14) - 🇪🇪 (VLESS)
  - (15) - 🇷🇺 (VLESS)
  - (16) - [OpenRay] 🇨🇦 CA-27502 (VLESS)
  - (17) - [OpenRay] 🇨🇦 CA-27487 (VLESS)
  - (18) - 🇰🇷 (VLESS)
  - (19) - [OpenRay] 🇨🇦 CA-27530 (VLESS)
  - (20) - [OpenRay] 🇨🇦 CA-27522 (VLESS)
  - (21) - [OpenRay] 🇨🇦 CA-26787 (VLESS)
  - (22) - 🇮🇹 Italy [*CIDR] t.me/rjsxrd (VLESS)
  - (23) - 🇮🇹 Italy [*CIDR] t.me/rjsxrd (VLESS)
  - '(24) - 🇳🇱 Netherlands | TG: @HardVpn_robot t.me/rjsxrd (VLESS)'
  - '(25) - 🇫🇷 France | TG: @HardVpn_robot t.me/rjsxrd (VLESS)'
  - (26) - 🇫🇷 (VLESS)
  - (27) - 🇮🇹 Italy [*CIDR] t.me/rjsxrd (VLESS)
  - (28) - 🇩🇪_德国_17 t.me/rjsxrd (VLESS)
  - (29) - 🇮🇹 Italy [*CIDR] t.me/rjsxrd (VLESS)
  - (30) - 🇯🇵 (VLESS)
  - (31) - 🇩🇪 德国 | DEU t.me/rjsxrd (VLESS)
  - (32) - 🇩🇪 (VLESS)
  - (33) - 🇳🇱_荷兰_25 t.me/rjsxrd (VLESS)
  - (34) - 🇩🇪_德国_19 t.me/rjsxrd (VLESS)
  - (35) - 🇩🇪_德国_21 t.me/rjsxrd (VLESS)
  - (36) - 14 (VLESS)
  - (37) - 🇩🇪 (VLESS)
  - (38) - 🇳🇱_荷兰_58 t.me/rjsxrd (VLESS)
  - (39) - 🇳🇱_荷兰_61 t.me/rjsxrd (VLESS)
  - '(40) - 🇨🇭 Switzerland | TG: @HardVpn_robot t.me/rjsxrd (VLESS)'
  - (41) - 🇦🇪_阿拉伯联合酋长国_57 t.me/rjsxrd (VLESS)
  - (42) - 🇵🇱_波兰_53 t.me/rjsxrd (VLESS)
  - (43) - 🇳🇱 荷兰 | NLD t.me/rjsxrd (VLESS)
  - (44) - 🇪🇸 (VLESS)
  - (45) - 🇳🇴_挪威_60 t.me/rjsxrd (VLESS)
  - '(46) - اگه میخوای قطع نشی جوین شو : @farsiproxy (VLESS)'
  - (47) - 🇩🇪 (VLESS)
  - (48) - 🇷🇺 Russia [*CIDR] t.me/rjsxrd (VLESS)
  - (49) - 🇷🇺 Russia [*CIDR] t.me/rjsxrd (VLESS)
  - (50) - 🇩🇪 (VLESS)
  - DIRECT
rules:
- MATCH,TOP
